    
    # key accelerometer
    # offset 0
    # key goal_lidar
    # offset 3
    # key gyro
    # offset 19
    # key hazards_lidar
    # offset 22
    # key jointpos_ankle_1
    # offset 38
    # key jointpos_ankle_2
    # offset 40
    # key jointpos_ankle_3
    # offset 42
    # key jointpos_ankle_4
    # offset 44
    # key jointpos_hip_1_y
    # offset 46
    # key jointpos_hip_1_z
    # offset 48
    # key jointpos_hip_2_y
    # offset 50
    # key jointpos_hip_2_z
    # offset 52
    # key jointpos_hip_3_y
    # offset 54
    # key jointpos_hip_3_z
    # offset 56
    # key jointpos_hip_4_y
    # offset 58
    # key jointpos_hip_4_z
    # offset 60
    # key jointvel_ankle_1
    # offset 62
    # key jointvel_ankle_2
    # offset 63
    # key jointvel_ankle_3
    # offset 64
    # key jointvel_ankle_4
    # offset 65
    # key jointvel_hip_1_y
    # offset 66
    # key jointvel_hip_1_z
    # offset 67
    # key jointvel_hip_2_y
    # offset 68
    # key jointvel_hip_2_z
    # offset 69
    # key jointvel_hip_3_y
    # offset 70
    # key jointvel_hip_3_z
    # offset 71
    # key jointvel_hip_4_y
    # offset 72
    # key jointvel_hip_4_z
    # offset 73
    # key magnetometer
    # offset 74
    # key touch_ankle_1a
    # offset 77
    # key touch_ankle_1b
    # offset 78
    # key touch_ankle_2a
    # offset 79
    # key touch_ankle_2b
    # offset 80
    # key touch_ankle_3a
    # offset 81
    # key touch_ankle_3b
    # offset 82
    # key touch_ankle_4a
    # offset 83
    # key touch_ankle_4b
    # offset 84
    # key vases_lidar
    # offset 85
    # key velocimeter
    # offset 101